### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by copy-ninja1** [AfriSplash-Remotely/AfriSplash-SuperAdmin#13]
![afrisplash_main_logo 2 (3)](https://user-images.githubusercontent.com/68874364/235102003-d8835c55-9e87-4f04-9d21-f0b63bdd9f71.png)
use this image to generate favicon of diffrent screen sizes

go to this website to generate faveicon https://favicomatic.com/

**Comment by sammy-code98** [comment]
done
